In [25]:
# 경고 메시지 무시
import warnings
warnings.filterwarnings(action='ignore') 

import pandas as pd

In [26]:
### 리스트를 데이터프레임으로 변환

list1=[1, 2, 3, 4, 5]

pd_s1=pd.DataFrame(list1)
pd_s1

   0
0  1
1  2
2  3
3  4
4  5

In [27]:
pd_s1['1열']=list1
pd_s1

   0  1열
0  1   1
1  2   2
2  3   3
3  4   4
4  5   5

In [28]:
pd_s2 = pd_s1.rename(columns={0:'0열'})
pd_s2

   0열  1열
0   1   1
1   2   2
2   3   3
3   4   4
4   5   5

In [30]:
pd_s1.rename(columns={0:'0열'}, inplace=True)
pd_s1

   0열  1열
0   1   1
1   2   2
2   3   3
3   4   4
4   5   5

In [31]:
pd_s2.drop(pd_s2.columns[0], axis=1, inplace=True)
pd_s2

   1열
0   1
1   2
2   3
3   4
4   5

In [32]:
### 2차원 리스트를 데이터프레임으로 변환

score=[['정약용', 70, 80, 100],
       ['이순신', 100, 80, 70],
       ['이율곡', 90, 95, 90]  ]
print(type(score))
score

<class 'list'>

[['정약용', 70, 80, 100], ['이순신', 100, 80, 70], ['이율곡', 90, 95, 90]]

In [33]:
score_df = pd.DataFrame(score)
print(type(score_df))
score_df

<class 'pandas.core.frame.DataFrame'>

     0    1   2    3
0  정약용   70  80  100
1  이순신  100  80   70
2  이율곡   90  95   90

In [34]:
score_df.columns=['이름', '국어', '영어', '수학']
score_df

    이름   국어  영어   수학
0  정약용   70  80  100
1  이순신  100  80   70
2  이율곡   90  95   90

In [35]:
score_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      3 non-null      object
 1   국어      3 non-null      int64
 2   영어      3 non-null      int64
 3   수학      3 non-null      int64
dtypes: int64(3), object(1)
memory usage: 228.0+ bytes

In [36]:
score_df.describe()

               국어         영어          수학
count    3.000000   3.000000    3.000000
mean    86.666667  85.000000   86.666667
std     15.275252   8.660254   15.275252
min     70.000000  80.000000   70.000000
25%     80.000000  80.000000   80.000000
50%     90.000000  80.000000   90.000000
75%     95.000000  87.500000   95.000000
max    100.000000  95.000000  100.000000

In [37]:
score_df.columns=['성명', 'kor', 'eng', 'mat']
score_df

    성명  kor  eng  mat
0  정약용   70   80  100
1  이순신  100   80   70
2  이율곡   90   95   90

In [38]:
score_df.index = score_df['성명']   ## 인덱스를 "성명"항목으로 변경
score_df

      성명  kor  eng  mat
성명
정약용  정약용   70   80  100
이순신  이순신  100   80   70
이율곡  이율곡   90   95   90

In [39]:
score_df.set_index('성명', drop=True, inplace=True) ## '성명'을 인덱스로 하고, '성명'항목 삭제
score_df

     kor  eng  mat
성명
정약용   70   80  100
이순신  100   80   70
이율곡   90   95   90

In [40]:
score_df.drop(['eng'], axis=1 , inplace=True)  # "eng"항목 삭제
score_df

     kor  mat
성명
정약용   70  100
이순신  100   70
이율곡   90   90

In [41]:
score_df.drop(['이순신'], axis=0 , inplace=True)  # "이순신""행" 삭제
score_df

     kor  mat
성명
정약용   70  100
이율곡   90   90

In [44]:
## 데이터 타입 변경

score_df1 = score_df.astype({'kor':float, 'mat':str})
score_df1

      kor  mat
성명
정약용  70.0  100
이율곡  90.0   90

In [45]:
score_df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, 정약용 to 이율곡
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   kor     2 non-null      float64
 1   mat     2 non-null      object
dtypes: float64(1), object(1)
memory usage: 48.0+ bytes

In [46]:
x=[0, 1, 2, 3, 4, 5]
y=[0, 2, 4, 6, 8, 10]
df=pd.DataFrame( )
df['x_value']=x
df['y_value']=y
df

   x_value  y_value
0        0        0
1        1        2
2        2        4
3        3        6
4        4        8
5        5       10

In [47]:
df['xy_value'] = df['x_value'] * df['y_value']
df

   x_value  y_value  xy_value
0        0        0         0
1        1        2         2
2        2        4         8
3        3        6        18
4        4        8        32
5        5       10        50