# groupby() 와 query()

DataFrame.groupby(기준항목).agg(사용하고자 하는 function들)
query() : 조건

In [1]:
# 경고 메시지 무시
import warnings
warnings.filterwarnings(action='ignore') 

import pandas as pd

In [2]:
exam = pd.read_csv('data/exam.csv')
exam

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
2    3       1    45       86       78
3    4       1    30       98       58
4    5       2    25       80       65
5    6       2    50       89       98
6    7       2    80       90       45
7    8       2    90       78       25
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
12  13       4    46       98       65
13  14       4    48       87       12
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [5]:
exam.groupby('nclass')[['math', 'english','science']].mean()

         math  english  science
nclass
1       46.25    94.75    61.50
2       61.25    84.25    58.25
3       45.00    86.50    39.25
4       56.75    84.75    55.00
5       78.00    74.25    83.25

In [6]:
exam.groupby('nclass').agg(mean_math   = ('math', 'mean'),         
                         sum_math    = ('math', 'sum'),          
                         median_math = ('math', 'median'),        
                         n = ('nclass', 'count'))

        mean_math  sum_math  median_math  n
nclass
1           46.25       185         47.5  4
2           61.25       245         65.0  4
3           45.00       180         47.5  4
4           56.75       227         53.0  4
5           78.00       312         79.0  4

In [7]:
exam.groupby('nclass').agg( { 'math' : ['max','min', 'mean'],   
                              'nclass' : 'count'})

       math            nclass
        max min   mean  count
nclass
1        60  30  46.25      4
2        90  25  61.25      4
3        65  20  45.00      4
4        75  46  56.75      4
5        89  65  78.00      4

In [8]:
exam.groupby('nclass').agg( { 'math' : ['max','min', 'mean'],  
                              'english' : ['max','min', 'mean'],
                              'nclass' : 'count'})

       math            english            nclass
        max min   mean     max min   mean  count
nclass
1        60  30  46.25      98  86  94.75      4
2        90  25  61.25      90  78  84.25      4
3        65  20  45.00      98  65  86.50      4
4        75  46  56.75      98  56  84.75      4
5        89  65  78.00      83  68  74.25      4

In [9]:
exam.query('nclass==1')

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78
3   4       1    30       98       58

In [10]:
## 수학 점수가 70점 이상인 데이터
exam.query('math >= 70')

    id  nclass  math  english  science
6    7       2    80       90       45
7    8       2    90       78       25
14  15       4    75       56       78
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [11]:
## 1반에서 수학 점수가 50점 이상인 학생
exam.query('nclass == 1 and math >= 50')  ## &

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60

In [13]:
# 1, 3, 5반 데이터 추출
# exam.query('nclass == 1 or nclass == 3 or nclass == 5')  ## |
exam.query('nclass in [1, 3, 5]')

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
2    3       1    45       86       78
3    4       1    30       98       58
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [14]:
# 1반 수학, 과학 점수 평균 구하기
exam.query('nclass == 1')[['math','science']].mean()

math       46.25
science    61.50
dtype: float64

In [15]:
## 변수를 이용해서 query 조건 만들기

a = int(input("몇 반 학생의 데이터 조회를 원하십니까? "))
exam.query('nclass == @a')

몇 반 학생의 데이터 조회를 원하십니까?  3

    id  nclass  math  english  science
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32