In [1]:
# 경고 메시지 무시
import warnings
warnings.filterwarnings(action='ignore') 

import pandas as pd
import numpy as np

# 데이터 병합 (merge(), concat())

In [4]:
# 중간고사 데이터 만들기
test1 = pd.DataFrame({'id'      : [1, 2, 3, 4, 5, 7],
                      'midterm' : [60, 80, 70, 90, 85, 20]})

# 기말고사 데이터 만들기
test2 = pd.DataFrame({'id'    : [1, 2, 3, 4, 5, 6],
                      'final' : [70, 83, 65, 95, 80, 10]})

display(test1)
display(test2)

   id  midterm
0   1       60
1   2       80
2   3       70
3   4       90
4   5       85
5   7       20

   id  final
0   1     70
1   2     83
2   3     65
3   4     95
4   5     80
5   6     10

In [5]:
# id 기준으로 merge
total = pd.merge( test1, test2, on='id', how='right')
total

   id  midterm  final
0   1     60.0     70
1   2     80.0     83
2   3     70.0     65
3   4     90.0     95
4   5     85.0     80
5   6      NaN     10

In [6]:
total = pd.merge( test1, test2, on='id')   # how = 'inner' (공통데이터_교집합)
total

   id  midterm  final
0   1       60     70
1   2       80     83
2   3       70     65
3   4       90     95
4   5       85     80

In [7]:
total = pd.merge( test1, test2, on='id', how='outer')  # 양쪽 모든 데이터 (합집합)
total

   id  midterm  final
0   1     60.0   70.0
1   2     80.0   83.0
2   3     70.0   65.0
3   4     90.0   95.0
4   5     85.0   80.0
5   6      NaN   10.0
6   7     20.0    NaN

In [8]:
group_a = pd.DataFrame({'id'   : [1, 2, 3, 4, 5],
                        'test' : [60, 80, 70, 90, 85]})

group_b = pd.DataFrame({'id'   : [5, 7, 8, 9, 10],
                        'test' : [70, 83, 65, 95, 80]})

In [9]:
# concat() 이용하여 합치기

group_all = pd.concat([group_a, group_b], ignore_index=True)
group_all

   id  test
0   1    60
1   2    80
2   3    70
3   4    90
4   5    85
5   5    70
6   7    83
7   8    65
8   9    95
9  10    80

# loc 와 iloc

In [10]:
# 예제 데이터프레임
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'Score': [85, 90, 95]
}
df = pd.DataFrame(data, index=['A', 'B', 'C'])
df

      Name  Age  Score
A    Alice   25     85
B      Bob   30     90
C  Charlie   35     95

In [11]:
df.loc[['A']]  # 행 'A' 조회

    Name  Age  Score
A  Alice   25     85

In [23]:
df.iloc[0, ]

Name     Alice
Age         25
Score       85
Name: A, dtype: object

In [22]:
df.iloc[:, 0]

A      Alice
B        Bob
C    Charlie
Name: Name, dtype: object

In [24]:
# Age가 28보다 큰 score 조회
df.loc[df['Age'] > 28 , 'Score']

B    90
C    95
Name: Score, dtype: int64