In [1]:
%run  start.py

제가 운영하는 스포츠센터는 트레이닝 붐 덕분에 지금까지 고객 수가 늘었습니다. 
그런데 최근 1년간 고객 수가 늘지 않는 것 같습니다. 
자주 이용하는 고객은 계속 오지만, 가끔 오는 고객은 어느새 오지 않는 경우도 생기는 것 같습니다. 
제대로 데이터를 분석한 적이 없어서 어떤 고객이 계속 이용하고 있는지조차 모릅니다. 
데이터분석을 하면 뭔가 알 수 있을까요?

In [ ]:
# use_log.csv : 이용이력, 기간은 2018.04~2019.03
# customer_master2.csv : 2019년 3월 말 시점의 회원 데이터 (이전 탈퇴 회원 포함)
# class_master.csv : 회원 구분 데이터(종일, 주간, 야간)
# campaign_master.csv : 행사 구분 데이터(입회비 유무 등)

## 데이터 읽기

In [2]:
uselog = pd.read_csv('data/use_log.csv')
print(len(uselog))
uselog.head(2)

197428

            log_id customer_id     usedate
0  L00000049012330    AS009373  2018-04-01
1  L00000049012331    AS015315  2018-04-01

In [3]:
customer = pd.read_csv('data/customer_master2.csv')
print(len(customer))
customer.head(2)

4192

,customer_id,name,class,gender,start_date,end_date,campaign_id,is_deleted
0,OA832399,XXXX,C01,F,2015-05-01 00:00:00,NaN,CA1,0
1,PL270116,XXXXX,C01,M,2015-05-01 00:00:00,NaN,CA1,0

In [4]:
class_master = pd.read_csv('data/class_master.csv')
print(len(class_master))
class_master

3

  class class_name  price
0   C01       0_종일  10500
1   C02       1_주간   7500
2   C03       2_야간   6000

In [5]:
campaign_master = pd.read_csv('data/campaign_master.csv')
print(len(campaign_master))
campaign_master

3

  campaign_id campaign_name
0         CA1          2_일반
1         CA2     0_입회비반액할인
2         CA3       1_입회비무료

## 고객 데이터 가공

In [6]:
## customer 와  class_master 를 결합
customer_join1 = pd.merge(customer, class_master, on="class", how="left")
customer_join1.head(2)

,customer_id,name,class,gender,start_date,end_date,campaign_id,is_deleted,class_name,price
0,OA832399,XXXX,C01,F,2015-05-01 00:00:00,NaN,CA1,0,0_종일,10500
1,PL270116,XXXXX,C01,M,2015-05-01 00:00:00,NaN,CA1,0,0_종일,10500

In [7]:
## customer_join1 과 campaign_master를 결합
customer_join2 = pd.merge(customer_join1, campaign_master, on="campaign_id", how="left")
customer_join2.head(2)

,customer_id,name,class,gender,start_date,end_date,campaign_id,is_deleted,class_name,price,campaign_name
0,OA832399,XXXX,C01,F,2015-05-01 00:00:00,NaN,CA1,0,0_종일,10500,2_일반
1,PL270116,XXXXX,C01,M,2015-05-01 00:00:00,NaN,CA1,0,0_종일,10500,2_일반

In [8]:
customer_join2.isnull().sum()

customer_id         0
name                0
class               0
gender              0
start_date          0
end_date         2842
campaign_id         0
is_deleted          0
class_name          0
price               0
campaign_name       0
dtype: int64

## 고객 데이터 집계

In [9]:
###  회원권별 카운트
customer_join2.groupby("class_name")[['customer_id']].count()

            customer_id
class_name
0_종일               2045
1_주간               1019
2_야간               1128

In [10]:
### 캠페인별 카운트
customer_join2.groupby("campaign_name")[["customer_id"]].count()

               customer_id
campaign_name
0_입회비반액할인              650
1_입회비무료                492
2_일반                  3050

In [11]:
### 성별 카운트
customer_join2.groupby("gender")[["customer_id"]].count()

        customer_id
gender
F              1983
M              2209

In [12]:
### 성별, 캠페인별 카운트
customer_join2.groupby(["gender","campaign_name"])[["customer_id"]].count()

                      customer_id
gender campaign_name
F      0_입회비반액할인              286
       1_입회비무료                251
       2_일반                  1446
M      0_입회비반액할인              364
       1_입회비무료                241
       2_일반                  1604

## 최근 고객 데이터

In [13]:
customer_join2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4192 entries, 0 to 4191
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    4192 non-null   object
 1   name           4192 non-null   object
 2   class          4192 non-null   object
 3   gender         4192 non-null   object
 4   start_date     4192 non-null   object
 5   end_date       1350 non-null   object
 6   campaign_id    4192 non-null   object
 7   is_deleted     4192 non-null   int64
 8   class_name     4192 non-null   object
 9   price          4192 non-null   int64
 10  campaign_name  4192 non-null   object
dtypes: int64(2), object(9)
memory usage: 360.4+ KB

In [14]:
import datetime
customer_join2["end_date"] = pd.to_datetime(customer_join2["end_date"])
customer_join2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4192 entries, 0 to 4191
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    4192 non-null   object
 1   name           4192 non-null   object
 2   class          4192 non-null   object
 3   gender         4192 non-null   object
 4   start_date     4192 non-null   object
 5   end_date       1350 non-null   datetime64[ns]
 6   campaign_id    4192 non-null   object
 7   is_deleted     4192 non-null   int64
 8   class_name     4192 non-null   object
 9   price          4192 non-null   int64
 10  campaign_name  4192 non-null   object
dtypes: datetime64[ns](1), int64(2), object(8)
memory usage: 360.4+ KB

In [16]:
customer_new = customer_join2.loc[customer_join2["end_date"].isna()] 
print(len(customer_new))

2842

In [17]:
customer_new.head(3)

,customer_id,name,class,gender,start_date,end_date,campaign_id,is_deleted,class_name,price,campaign_name
0,OA832399,XXXX,C01,F,2015-05-01 00:00:00,NaT,CA1,0,0_종일,10500,2_일반
1,PL270116,XXXXX,C01,M,2015-05-01 00:00:00,NaT,CA1,0,0_종일,10500,2_일반
2,OA974876,XXXXX,C01,M,2015-05-01 00:00:00,NaT,CA1,0,0_종일,10500,2_일반

## 이용 이력 데이터 (uselog)

In [18]:
uselog.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 197428 entries, 0 to 197427
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   log_id       197428 non-null  object
 1   customer_id  197428 non-null  object
 2   usedate      197428 non-null  object
dtypes: object(3)
memory usage: 4.5+ MB

In [19]:
uselog["usedate"] = pd.to_datetime(uselog["usedate"])

In [20]:
uselog["년월"] = uselog["usedate"].dt.strftime("%Y%m")
uselog

                 log_id customer_id    usedate      년월
0       L00000049012330    AS009373 2018-04-01  201804
1       L00000049012331    AS015315 2018-04-01  201804
2       L00000049012332    AS040841 2018-04-01  201804
3       L00000049012333    AS046594 2018-04-01  201804
4       L00000049012334    AS073285 2018-04-01  201804
...                 ...         ...        ...     ...
197423  L00000049209753    TS977703 2019-03-31  201903
197424  L00000049209754    TS979550 2019-03-31  201903
197425  L00000049209755    TS995299 2019-03-31  201903
197426  L00000049209756    TS995853 2019-03-31  201903
197427  L00000049209757    TS999079 2019-03-31  201903

[197428 rows x 4 columns]

In [21]:
uselog.groupby("년월")[['log_id']].count()

        log_id
년월
201804   16460
201805   16913
201806   16994
201807   16954
201808   16674
201809   16471
201810   15989
201811   15697
201812   16383
201901   16363
201902   16375
201903   16155

In [24]:
uselog_months = uselog.groupby(["년월", "customer_id"], as_index=False)[['usedate']].count()
uselog_months

           년월 customer_id  usedate
0      201804    AS002855        4
1      201804    AS009013        2
2      201804    AS009373        3
3      201804    AS015315        6
4      201804    AS015739        7
...       ...         ...      ...
36837  201903    TS995853        8
36838  201903    TS998593        8
36839  201903    TS999079        3
36840  201903    TS999231        6
36841  201903    TS999855        4

[36842 rows x 3 columns]

In [25]:
uselog_months.rename(columns={"usedate":"count"}, inplace=True)
uselog_months

           년월 customer_id  count
0      201804    AS002855      4
1      201804    AS009013      2
2      201804    AS009373      3
3      201804    AS015315      6
4      201804    AS015739      7
...       ...         ...    ...
36837  201903    TS995853      8
36838  201903    TS998593      8
36839  201903    TS999079      3
36840  201903    TS999231      6
36841  201903    TS999855      4

[36842 rows x 3 columns]

In [28]:
uselog_customer = uselog_months.groupby("customer_id")["count"].agg(["mean", "median", "max", "min" ])
uselog_customer

                 mean  median  max  min
customer_id
AS002855     4.500000     5.0    7    2
AS008805     4.000000     4.0    8    1
AS009013     2.000000     2.0    2    2
AS009373     5.083333     5.0    7    3
AS015233     7.545455     7.0   11    4
...               ...     ...  ...  ...
TS995853     9.500000     9.5   11    8
TS998593     8.142857     8.0    9    7
TS999079     4.916667     5.5    9    2
TS999231     4.666667     5.0    8    1
TS999855     4.583333     4.0    7    3

[4192 rows x 4 columns]

In [ ]:
uselog_customer = uselog_customer.reset_index(drop=False)
uselog_customer

     customer_id      mean  median  max  min
0       AS002855  4.500000     5.0    7    2
1       AS008805  4.000000     4.0    8    1
2       AS009013  2.000000     2.0    2    2
3       AS009373  5.083333     5.0    7    3
4       AS015233  7.545455     7.0   11    4
...          ...       ...     ...  ...  ...
4187    TS995853  9.500000     9.5   11    8
4188    TS998593  8.142857     8.0    9    7
4189    TS999079  4.916667     5.5    9    2
4190    TS999231  4.666667     5.0    8    1
4191    TS999855  4.583333     4.0    7    3

[4192 rows x 5 columns]

## uselog 데이터로 정기이용 여부 플래그 작성

In [29]:
uselog.head(3)

            log_id customer_id    usedate      년월
0  L00000049012330    AS009373 2018-04-01  201804
1  L00000049012331    AS015315 2018-04-01  201804
2  L00000049012332    AS040841 2018-04-01  201804

In [30]:
uselog["weekday"] = uselog["usedate"].dt.weekday
uselog

## 월요일~일요일 : 0~6

                 log_id customer_id    usedate      년월  weekday
0       L00000049012330    AS009373 2018-04-01  201804        6
1       L00000049012331    AS015315 2018-04-01  201804        6
2       L00000049012332    AS040841 2018-04-01  201804        6
3       L00000049012333    AS046594 2018-04-01  201804        6
4       L00000049012334    AS073285 2018-04-01  201804        6
...                 ...         ...        ...     ...      ...
197423  L00000049209753    TS977703 2019-03-31  201903        6
197424  L00000049209754    TS979550 2019-03-31  201903        6
197425  L00000049209755    TS995299 2019-03-31  201903        6
197426  L00000049209756    TS995853 2019-03-31  201903        6
197427  L00000049209757    TS999079 2019-03-31  201903        6

[197428 rows x 5 columns]

In [31]:
uselog_weekday = uselog.groupby(["customer_id","년월","weekday"],
                as_index=False).count()[["customer_id","년월", "weekday","log_id"]]
uselog_weekday.head(3)

  customer_id      년월  weekday  log_id
0    AS002855  201804        5       4
1    AS002855  201805        2       1
2    AS002855  201805        5       4

In [32]:
uselog_weekday.rename(columns={"log_id":"count"}, inplace=True)
uselog_weekday

      customer_id      년월  weekday  count
0        AS002855  201804        5      4
1        AS002855  201805        2      1
2        AS002855  201805        5      4
3        AS002855  201806        5      5
4        AS002855  201807        1      1
...           ...     ...      ...    ...
93328    TS999855  201901        1      1
93329    TS999855  201901        5      4
93330    TS999855  201901        6      1
93331    TS999855  201902        5      4
93332    TS999855  201903        5      4

[93333 rows x 4 columns]

In [33]:
uselog_weekday = uselog_weekday.groupby("customer_id",as_index=False)[["customer_id", "count"]].max()
uselog_weekday

     customer_id  count
0       AS002855      5
1       AS008805      4
2       AS009013      2
3       AS009373      5
4       AS015233      5
...          ...    ...
4187    TS995853      5
4188    TS998593      5
4189    TS999079      5
4190    TS999231      5
4191    TS999855      5

[4192 rows x 2 columns]

In [34]:
uselog_weekday["routine_flg"] = 0

uselog_weekday.loc[uselog_weekday["count"] >= 4, "routine_flg"] = 1
uselog_weekday.head()

  customer_id  count  routine_flg
0    AS002855      5            1
1    AS008805      4            1
2    AS009013      2            0
3    AS009373      5            1
4    AS015233      5            1

## 고객 데이터와 이용이력 데이터를 결합

In [35]:
uselog_customer.head(2)

             mean  median  max  min
customer_id
AS002855      4.5     5.0    7    2
AS008805      4.0     4.0    8    1

In [36]:
customer_join2.head(2)

,customer_id,name,class,gender,start_date,end_date,campaign_id,is_deleted,class_name,price,campaign_name
0,OA832399,XXXX,C01,F,2015-05-01 00:00:00,NaT,CA1,0,0_종일,10500,2_일반
1,PL270116,XXXXX,C01,M,2015-05-01 00:00:00,NaT,CA1,0,0_종일,10500,2_일반

In [37]:
customer_join3 = pd.merge(customer_join2, uselog_customer, on="customer_id", how="left")
customer_join3.head(3)

,customer_id,name,class,gender,start_date,end_date,campaign_id,is_deleted,class_name,price,campaign_name,mean,median,max,min
0,OA832399,XXXX,C01,F,2015-05-01 00:00:00,NaT,CA1,0,0_종일,10500,2_일반,4.833333,5.0,8,2
1,PL270116,XXXXX,C01,M,2015-05-01 00:00:00,NaT,CA1,0,0_종일,10500,2_일반,5.083333,5.0,7,3
2,OA974876,XXXXX,C01,M,2015-05-01 00:00:00,NaT,CA1,0,0_종일,10500,2_일반,4.583333,5.0,6,3

In [38]:
customer_join4 = pd.merge(customer_join3,uselog_weekday[["customer_id", "routine_flg"]],
                                                      on="customer_id", how="left")
customer_join4["start_date"]=pd.to_datetime(customer_join4["start_date"])
customer_join4.head(3)

,customer_id,name,class,gender,start_date,end_date,campaign_id,is_deleted,class_name,price,campaign_name,mean,median,max,min,routine_flg
0,OA832399,XXXX,C01,F,2015-05-01,NaT,CA1,0,0_종일,10500,2_일반,4.833333,5.0,8,2,1
1,PL270116,XXXXX,C01,M,2015-05-01,NaT,CA1,0,0_종일,10500,2_일반,5.083333,5.0,7,3,1
2,OA974876,XXXXX,C01,M,2015-05-01,NaT,CA1,0,0_종일,10500,2_일반,4.583333,5.0,6,3,1

## 회원 기간 계산

In [39]:
from dateutil.relativedelta import relativedelta

In [40]:
### test

a = relativedelta(pd.to_datetime("2026-08-09"), pd.to_datetime("2001-05-10"))
print(a)
print(a.years)
print(a.months)

relativedelta(years=+25, months=+2, days=+30)
25
2

In [41]:
customer_join4["calc_date"] = customer_join4["end_date"]
customer_join4["calc_date"] = customer_join4["calc_date"].fillna(pd.to_datetime("20190331"))
customer_join4.head(3)

,customer_id,name,class,gender,start_date,end_date,campaign_id,is_deleted,class_name,price,campaign_name,mean,median,max,min,routine_flg,calc_date
0,OA832399,XXXX,C01,F,2015-05-01,NaT,CA1,0,0_종일,10500,2_일반,4.833333,5.0,8,2,1,2019-03-31
1,PL270116,XXXXX,C01,M,2015-05-01,NaT,CA1,0,0_종일,10500,2_일반,5.083333,5.0,7,3,1,2019-03-31
2,OA974876,XXXXX,C01,M,2015-05-01,NaT,CA1,0,0_종일,10500,2_일반,4.583333,5.0,6,3,1,2019-03-31

In [42]:
customer_join4["membership_p"] =0

for i in range(len(customer_join4)):
    delta = relativedelta( customer_join4.loc[i, "calc_date"], customer_join4.loc[i, "start_date"] )
    customer_join4.loc[i, "membership_p"] = delta.years*12 + delta.months    ## 개월 수 계산
    
customer_join4.head(3)

,customer_id,name,class,gender,start_date,end_date,campaign_id,is_deleted,class_name,price,campaign_name,mean,median,max,min,routine_flg,calc_date,membership_p
0,OA832399,XXXX,C01,F,2015-05-01,NaT,CA1,0,0_종일,10500,2_일반,4.833333,5.0,8,2,1,2019-03-31,46
1,PL270116,XXXXX,C01,M,2015-05-01,NaT,CA1,0,0_종일,10500,2_일반,5.083333,5.0,7,3,1,2019-03-31,46
2,OA974876,XXXXX,C01,M,2015-05-01,NaT,CA1,0,0_종일,10500,2_일반,4.583333,5.0,6,3,1,2019-03-31,46

In [43]:
customer_join4.groupby("routine_flg").count()[["customer_id"]]

             customer_id
routine_flg
0                    779
1                   3413

In [44]:
customer_end = customer_join4.loc[customer_join4["is_deleted"]==1]
customer_end.describe()

,start_date,end_date,is_deleted,price,mean,median,max,min,routine_flg,calc_date,membership_p
count,1350,1350,1350.0,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350,1350.000000
mean,2018-01-20 10:45:20,2018-10-17 16:23:28,1.0,8595.555556,3.865474,3.621852,6.461481,1.821481,0.456296,2018-10-17 16:23:28,8.026667
min,2016-05-01 00:00:00,2018-04-30 00:00:00,1.0,6000.000000,1.000000,1.000000,1.000000,1.000000,0.000000,2018-04-30 00:00:00,1.000000
25%,2017-10-01 00:00:00,2018-06-30 00:00:00,1.0,6000.000000,3.000000,3.000000,4.000000,1.000000,0.000000,2018-06-30 00:00:00,4.000000
50%,2018-03-01 00:00:00,2018-10-31 00:00:00,1.0,7500.000000,4.000000,4.000000,7.000000,2.000000,0.000000,2018-10-31 00:00:00,7.000000
75%,2018-06-03 00:00:00,2019-01-31 00:00:00,1.0,10500.000000,4.666667,4.500000,8.000000,2.000000,1.000000,2019-01-31 00:00:00,11.000000
max,2019-02-11 00:00:00,2019-03-31 00:00:00,1.0,10500.000000,9.000000,9.000000,13.000000,8.000000,1.000000,2019-03-31 00:00:00,23.000000
std,NaN,NaN,0.0,1949.163652,1.246385,1.270847,2.584021,0.976361,0.498271,NaN,5.033692

In [45]:
customer_stay = customer_join4.loc[customer_join4["is_deleted"]==0]
customer_stay.describe()

,start_date,end_date,is_deleted,price,mean,median,max,min,routine_flg,calc_date,membership_p
count,2842,0,2842.0,2842.000000,2842.000000,2842.000000,2842.000000,2842.000000,2842.000000,2842,2842.000000
mean,2017-04-03 22:42:28.627726848,NaT,0.0,8542.927516,6.030288,6.024279,8.471147,3.620690,0.984166,2019-03-31 00:00:00,22.970443
min,2015-05-01 00:00:00,NaT,0.0,6000.000000,3.166667,3.000000,5.000000,1.000000,0.000000,2019-03-31 00:00:00,0.000000
25%,2016-05-01 00:00:00,NaT,0.0,6000.000000,4.833333,5.000000,7.000000,2.000000,1.000000,2019-03-31 00:00:00,11.000000
50%,2017-04-01 00:00:00,NaT,0.0,7500.000000,5.583333,5.500000,8.000000,3.000000,1.000000,2019-03-31 00:00:00,23.000000
75%,2018-04-05 00:00:00,NaT,0.0,10500.000000,7.178030,7.000000,10.000000,5.000000,1.000000,2019-03-31 00:00:00,34.000000
max,2019-03-15 00:00:00,NaT,0.0,10500.000000,12.000000,12.000000,14.000000,12.000000,1.000000,2019-03-31 00:00:00,46.000000
std,NaN,NaN,0.0,1977.189779,1.553587,1.599765,1.571048,2.030488,0.124855,NaN,13.746761

탈퇴회원의 평균, 중앙, 최대, 최소값은 모두 지속 회원보다 작음을 알 수 있다.
 특히, 평균과 중앙값은 큰 차이가 있음.
 매월 최대 이용 횟수의 평균값은 지속 회원이 높다.
 routine_flg 의 평균값은 차이가 크게 나서, 지속회원은 0.95로 많은 회원이 정기적으로 이용하고 있다는 것을 알 수 있음.
 반면, 탈퇴 회원은 0.45로 거의 절반은 랜덤하게 이용하고 있다고 판단됨.

In [46]:
customer_join4.to_csv("data/customer_join4.csv", index=False,  encoding='utf-8-sig')